version: '3.8'
services:
  filter-api:
    build:
      context: .
      dockerfile: filter-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/filter
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  filter-ui:
    build:
      context: .
      dockerfile: filter-ui/Dockerfile
    ports:
      - "80:80"
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: filter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
